### ISSUE TITLE
Notes not working in latest dokuwiki

### ISSUE THREAD

**Issue by shawndibble** [bojidar-bg/dokuwiki-callflow-plugin#5]
I am using the latest version of dokuwiki with your plugin. Almost all functions work, however using your sample syntax, you can see that the note titled PHP is missing from the graph.

![example](https://cloud.githubusercontent.com/assets/1980293/4290133/2dc63450-3db9-11e4-9d55-f4174e7e439f.png)

**Comment by bojidar-bg** [comment]
Wierd, I can still reproduce this...
